### ISSUE TITLE
Watir fails to find element using custom attribute in IE11

### ISSUE THREAD

**Issue by rails4sandeep** [watir/watir#879] opened 2019-09-02 06:39 UTC
## Meta -

Watir Version: watir (6.16.5)
Selenium Version: selenium-webdriver (3.142.3)
Browser Version: IE11
Browser Driver Version: 2.41 
OS Version: Windows 10

## Expected Behavior -

Be able to access an element using a custom attribute. Works in all browsers except IE11

## Actual Behavior -

Watir fails to find an element using a custom attribute in IE11.

## Steps to reproduce -

page element: 

`<input placeholder="Enter username" type="text" data-automation-key="login-page-username" data-automation-value="" value="">`

Watir Code:

```
   @b.text_field(:data_automation_key => "login-page-username").wait_until(&:present?)
    @b.text_field(:data_automation_key => "login-page-username").scroll.to
    @b.text_field(:data_automation_key => "login-page-username").send_keys 'xyz@gmail.com'
```

Watir DEBUG INFO:

```
2019-09-02 16:19:56 INFO Watir Converted {:data_automation_key=>"login-page-username", :tag_name=>"input"} to {:xpath=>".//*[local-name()='input'][not(@type) or (translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='file' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='radio' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='checkbox' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='submit' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='reset' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='image' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='button' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='hidden' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='range' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='color' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='date' and translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸŽŠŒ','abcdefghijklmnopqrstuvwxyzàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿžšœ')!='datetime-local')][@data-automation-key='login-page-username']"}
```

Watir Error:

```
Watir::Wait::TimeoutError:
       timed out after 30 seconds, waiting for true condition on #<Watir::TextField: located: true; {:data_automation_key=>"login-page-username", :tag_name=>"input"}>
     # /Users/sandeepkumar/.rvm/gems/ruby-2.6.3/gems/watir-6.16.5/lib/watir/wait.rb:46:in `until'
     # /Users/sandeepkumar/.rvm/gems/ruby-2.6.3/gems/watir-6.16.5/lib/watir/wait.rb:125:in `wait_until'
```

Other useful information:

```
{
  "64bit": true,
  "acceptSslCert": false,
  "acceptSslCerts": false,
  "browser": "ie",
  "browserName": "internet explorer",
  "browser_name": "IE",
  "browser_version": "11.0",
  "browserstack.appiumLogs": "false",
  "browserstack.bfcache": "0",
  "browserstack.debug": "false",
  "browserstack.ie.driver": "2.41",
  "browserstack.ie.noFlash": "false",
  "browserstack.local": "false",
  "browserstack.networkLogs": "false",
  "browserstack.selenium.jar.version": "3.14.0",
  "browserstack.seleniumLogs": "true",
  "browserstack.video": "true",
  "browserstack.video.disableWaterMark": "true",
  "cssSelectorsEnabled": true,
  "detected_language": "selenium\u002f3.142.3 (ruby macosx)",
  "initialBrowserUrl": "about:blank",
  "javascriptEnabled": false,
  "nativeEvents": false,
  "orig_os": "win10",
  "os": "Windows",
  "osVersion": "10",
  "os_version": "10",
  "platform": "WINDOWS",
  "proxy_type": "node",
  "rotatable": false,
  "takesScreenshot": false,
  "version": "11.0"
}
```

**Comment by kapoorlakshya** [comment] 2019-09-10 21:51
@rails4sandeep I am unable to reproduce this in IE 11 using `IEDriverServer` v3.141.49 on Windows 10. The text field (used HTML from you post) is found and set successfully for me.

> Browser Driver Version: 2.41

That version is five years old. I recommend you give [v3.141.59](https://selenium-release.storage.googleapis.com/index.html?path=3.141/) a try. There is also a 3.150 available, but I've been running into problems with that.

**Comment by jkotests** [comment] 2020-01-10 17:18
@rails4sandeep , I am going to close this due to the old driver version. If you still have the problem with the latest driver, we can re-open this.

**Closed as completed by jkotests** 2020-01-10 17:18 UTC
