### ISSUE TITLE
Warning: Fixnum is deprecated & Error: TableCell 

### ISSUE THREAD

**Issue by coloradojay** [watir/watir#511] opened 2016-12-29 05:43 UTC
After upgrading to Ruby 2.4 and while attempting to require watir in irb, received the following warning & error: 

`/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:17: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:137: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:138: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:139: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:140: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:142: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:158: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:161: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:168: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:169: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:301: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:306: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:307: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:316: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:321: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:322: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:335: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:361: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:364: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:366: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:413: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:418: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:420: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:427: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:437: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:442: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:443: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:469: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:475: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:476: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:478: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:507: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:508: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:592: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:595: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:626: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:627: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:628: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:629: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:641: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:674: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:676: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:724: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:725: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:726: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:727: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:733: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:734: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:816: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:831: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/html_elements.rb:845: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:8: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:55: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:61: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:62: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:72: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:73: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:74: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:75: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:109: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:110: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:116: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:117: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:118: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:119: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:120: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:121: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:127: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:128: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:129: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:130: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:136: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:137: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:139: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:140: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:177: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:178: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:179: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:180: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:186: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:193: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:224: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:225: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:226: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:227: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:244: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:245: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:246: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:247: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:255: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:280: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:281: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:282: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:283: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:289: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:290: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:291: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:292: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:298: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:299: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:300: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:306: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:307: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:308: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:309: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:310: warning: constant ::Fixnum is deprecated
/gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/svg_elements.rb:311: warning: constant ::Fixnum is deprecated

NameError: undefined method `col_span' for class `Watir::TableCell'
from /gems/ruby-2.4.0/gems/watir-6.0.3/lib/watir/elements/table_cell.rb:3:in `alias_method'`

Any help or insight into resolving the error + warnings?

**Comment by p0deje** [comment] 2016-12-29 05:44
Duplicate of #510. Please, take a look at that one.

**Closed as completed by p0deje** 2016-12-29 05:44 UTC
