### ISSUE TITLE
FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by yegor256** [watir/watir#877] opened 2019-08-23 02:41 UTC
It seems that you are trying to modify the arguments I'm sending you:

```
FrozenError: can't modify frozen String
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:234:in `slice!'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:234:in `equal_pair'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:53:in `predicate_expression'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:43:in `process_attribute'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:113:in `block in class_string'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:113:in `map'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:113:in `class_string'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder/xpath.rb:27:in `build'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder.rb:150:in `build_wd_selector'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/locators/element/selector_builder.rb:34:in `build'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/element_collection.rb:41:in `build'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/element_collection.rb:16:in `initialize'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/elements/html_elements.rb:1159:in `new'
            /Users/yegor/.rvm/gems/ruby-2.6.0/gems/watir-6.16.5/lib/watir/elements/html_elements.rb:1159:in `divs'
```

See how rude it is! :)

I'm doing exactly this:

```ruby
browser.divs(class: ['a', '!b'])
```

**Comment by jkotests** [comment] 2019-08-23 13:40
@yegor256 , do you know if the problem is specific to Ruby 2.6? We have tests running for Ruby 2.3 to 2.5 and I think we have a test for this.

**Comment by avispatech-dev** [comment] 2019-09-22 01:54
I am having the same issue on ruby 2.6.3 and its affecting it even when calling a new Watir::Browser

`/app/vendor/bundle/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/firefox/binary.rb:134:in 'path'`

This is happening to me because it seems that firefox can't be found and it raises an error when concatenating a String

**Comment by avispatech-dev** [comment] 2019-09-22 03:06
Now I switched to ruby 2.5.3 and the problem persists.
The error comes from Selenium, here is the issue https://github.com/SeleniumHQ/selenium/issues/7365

**Comment by jkotests** [comment] 2020-01-10 17:20
This is fixed in newer Selenium versions.

**Closed as completed by jkotests** 2020-01-10 17:20 UTC
