### ISSUE TITLE
Not waiting until the element is writable

### ISSUE THREAD

**Issue by abotalov** [watir/watir#753] opened 2018-06-29 13:40 UTC
I found this in Nerodia that has the same issue.

## Expected Behavior -
When `el.set(...)` is invoked, I expect Watir / Nerodia to wait for an element to be writable.

## Actual Behavior -
When `el.set(...)` is invoked, Watir / Nerodia doesn't wait for the element to be writable.
An error is raised on this line - https://github.com/watir/watir/blame/master/lib/watir/elements/element.rb#L671:
```rb
raise_disabled unless precondition == :wait_for_writable || precondition == :wait_for_enabled
```

Elements may appear in DOM some hundreds of milliseconds before they become interactable.

**Comment by titusfortner** [comment] 2018-07-08 00:31
can you give me something reproducible? I just added a spec that indicates that the code is working as expected: https://github.com/watir/watir/blob/master/spec/watirspec/elements/text_field_spec.rb#L210

**Comment by titusfortner** [comment] 2018-07-08 02:18
Ok, I'm guessing this is a duplicate of #675 which I just pushed a fix for. We can reopen if 6.12 doesn't fix it.

**Closed as completed by titusfortner** 2018-07-08 02:18 UTC
