### ISSUE TITLE
NoMethodError: undefined method `-' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [watir/watir#881] opened 2019-09-10 15:43 UTC
Watir Version: 6.16.5

```
NoMethodError: undefined method `-' for nil:NilClass
	/var/lib/gems/2.6.0/gems/watir-6.16.5/lib/watir/wait/timer.rb:26:in `remaining_time'
	/var/lib/gems/2.6.0/gems/watir-6.16.5/lib/watir/elements/element.rb:803:in `rescue in element_call'
	/var/lib/gems/2.6.0/gems/watir-6.16.5/lib/watir/elements/element.rb:790:in `element_call'
	/var/lib/gems/2.6.0/gems/watir-6.16.5/lib/watir/elements/element.rb:1
```

**Comment by Rajagopalan-M** [comment] 2019-11-20 05:18
@yegor256  Yes, this is what I am getting now too. 

@jkotests  @titusfortner  Can you please let me know what's the problem here? 

I am able to guess why this error might be happening 

here is the small code snippet

```
current_time=nil
@end_time - current_time
```
Execution of the above code gives the same error 

>  `<main>': undefined method `-' for nil:NilClass (NoMethodError)

So this tells me the current time variable is not receiving any value.

**Comment by Rajagopalan-M** [comment] 2019-11-20 07:22
The problem is here

This one returns nil now

>  if defined?(Process::CLOCK_MONOTONIC)
>         def current_time
>           Process.clock_gettime(Process::CLOCK_MONOTONIC)
>         end
>       else
>         def current_time
>           ::Time.now.to_f
>         end
>       end

@jkotests  Can you please take a look at this? the variable current_time is somehow receiving the nil value and the aforementioned error is thrown now. 

Note: It's not returning nil all the time.

**Comment by jkotests** [comment] 2019-11-20 16:06
@Rajagopalan-M do you know how to reproduce the problem?

**Comment by Rajagopalan-M** [comment] 2019-11-21 02:31
@jkotests 

I have created a framework here in which all scenarios are running sequentially and this time I haven't had this problem, but when I added a feature to run all the scenarios in parallel, this problem is showing up. 

You take any watir code(please include textarea field into that because that's where this problem occurs most of the time ) and you insert into my thread below and execute it.

An example program here

> threads = []
> 10.times do
>   threads << Thread.new do
>     require 'watir'
>     b = Watir::Browser.new
>     b.goto 'www.google.com'
>     b.text_field(name: 'q').set 'rajagopalan'
>     ....
>     ....
>     ....
>     ....
>   end
> end
> 
> threads.each(&:join)

Please include `textarea` in your code, atleast create some 20 lines of watir code inside the 10.times do end.

::Time.now that's returning nil at some point in time, I don't understand the reason behind this. 

You may notice the little log from my execution

```
select               :  Employers Liability Limits(changes) | $500,000 / $500,000 / $500,000
clickButton          :  Continue On Rating Info Page
clickButton          :  Continue On Loss Info Page
clickButton          :  Continue On General Info Page
clickButton          :  Continue on Excl/Incl Page
clickButton          :  Continue On Name Insured Page
clickLink            :  Adding the coverage endorsement form for WC000109C(changes)
typeInTextArea       :  Description | test12
****************ERROR*************************
undefined method `-' for nil:NilClass
**********************************************
------------End-----------------
```

**Comment by jkotests** [comment] 2019-11-21 06:54
Thanks @Rajagopalan-M , your example helped me understand the problem.

Note that given the exception, it is actually `@end_time` that is `nil`, not `current_time`. 

At the start of `#element_call`, where all the magic waiting happens, we initialize a timer and set `@end_time` to a value. At the end, we reset the timer, which sets `@end_time` back to `nil`. To handle nested `#element_call` we share the timer - allowing us to wait just a single `default_timeout` rather than multiple timeouts added together.

The problem is that the shared timer is not thread safe. For example, thread 1 will initialize the timer and reset it when its done. Thread 2 is using the same timer and may check `@end_time` after it has been reset in thread 1.

Example that reproduces the issue:

~~~~~~~~
Watir.default_timeout = 5 # so we don't have to wait as long
threads = []
10.times do |i|
  threads << Thread.new do
    browser = Watir::Browser.new
    begin 
      browser.head.click        
    rescue Watir::Exception::UnknownObjectException
      puts 'Watir::Exception::UnknownObjectException'
    rescue NoMethodError
      puts 'NoMethodError'
    end 
  end
end
threads.each(&:join)
~~~~~~~~

**Comment by Rajagopalan-M** [comment] 2019-11-21 09:15
@jkotests  It's an excellent find. Thanks. 

When can I expect the fix for this?

**Comment by titusfortner** [comment] 2019-11-21 15:56
tbh, this one is going to be low on the priority list. Can you use a gem like parallel_test rather than trying to use threads directly in your test code?

**Comment by titusfortner** [comment] 2019-11-21 15:59
I think #835 would address this issue if/when it ever gets implemented.

**Comment by jkotests** [comment] 2019-11-22 02:08
@titusfortner would pushing the timer to the browser instance solve the problem? Presumably no one would be doing 2 things in the browser instance at once?

**Comment by Rajagopalan-M** [comment] 2019-11-22 02:44
> tbh, this one is going to be low on the priority list. Can you use a gem like parallel_test rather than trying to use threads directly in your test code?

Okay. Thanks.

**Comment by Rajagopalan-M** [comment] 2019-11-22 02:44
> 
> 
> @titusfortner would pushing the timer to the browser instance solve the problem? Presumably no one would be doing 2 things in the browser instance at once?

That would help.

**Comment by Rajagopalan-M** [comment] 2019-11-25 16:32
@jkotests Hi Justin, I have resolved this problem by requiring the watir gem for each testcase. Previously I was requiring the WATIR gem once before all the testcases, now I changed to require the watir gem in the start of each testcase. This problem was solved now for my case.

**Comment by Rajagopalan-M** [comment] 2019-11-26 03:06
@jkotests Any update on this?

**Comment by Rajagopalan-M** [comment] 2019-11-26 11:15
@jkotests I have solved this problem by requiring watir gem for every thread it starts, something like this
```

threads<<Thread.new do
require 'watir'
............
...........
...........
end
```

**Comment by Rajagopalan-M** [comment] 2019-11-27 03:09
@jkotests Hi, I thought it was resolved, but it was not. It is still showing up. Can you give the fix as you said above like *" pushing the timer to the browser instance solve the problem? "*

If you can't do in the master, can you tell me the way where I can write some workaround in my project?

**Comment by jkotests** [comment] 2019-11-27 03:54
@Rajagopalan-M , I was thinking something like https://github.com/jkotests/watir/commit/0368c64cf621c80349f55907dd707622f4d6ba26 . It doesn't obviously break the specs, but I haven't had time to thoroughly test it.

**Comment by Rajagopalan-M** [comment] 2019-11-27 04:18
@jkotests Thank you very much. I will do the test and let you know.

**Comment by Rajagopalan-M** [comment] 2019-11-28 03:50
@jkotests Hey Dude! Perfect! It solved the problem. You are a genius really! 

I re-ran my entire suite couple of times again, that error doesn't show up. I completely believe this should be a perfect fix. Can you push this changes into master?

**Comment by Rajagopalan-M** [comment] 2020-08-27 06:50
@titusfortner 

Hi Titus, Can you please merge this? @jkotests  solution works perfectly for me all these days. Since I execute test cases parallelly I get this problem.

**Comment by titusfortner** [comment] 2020-08-27 08:32
merged https://github.com/watir/watir/commit/25db3b303cb543b67d0ded2e5873cadff64a6675

**Closed as completed by titusfortner** 2020-08-27 08:32 UTC
Labels: bug

**Comment by Rajagopalan-M** [comment] 2020-08-27 08:37
@titusfortner  Thank you very much
