### ISSUE TITLE
Intermittent `EOFError end of file reached`

### ISSUE THREAD

**Issue by jdwolk** [watir/watir#892] opened 2020-03-05 22:44 UTC
## Meta -
Watir Version: 6.16.5
Selenium Version: ?
    * Selenium Webdriver Version: 3.142.6
Browser Version: Chrome 79.0.3945.79
Browser Driver Version: Chrome webdriver 79.0.3945.36
OS Version: Debian Buster (Dockerized, running in AWS ECS)

## Expected Behavior -
I'm able to interact normally with chrome via watir without this error occurring

## Actual Behavior -
Various calls to watir intermittently produce an `EOFError: end of file reached` (or, less often, an `EOFError` with `Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9516 (Connection refused - connect(2) for "127.0.0.1" port 9516),`).

## Steps to reproduce -
The error is intermittent so we haven't identified reproducible steps.

We're running watir for screen scraping, not for acceptance testing. It runs in a deployed dockerized environment in AWS ECS in a `sidekiq` worker process.

Some watir method calls that have produced the error include:

```
browser.html

browser.form(method: 'POST')

browser.goto('https://www.google.com')

form = browser.forms.first
form.submit

form = browser.forms.first
form.exists?

form = browser.forms.first
form.text_field(name: 'text').set('foobar')

options[:args] = [
  '--no-sandbox',
  '--disable-dev-shm-usage',
  '--disable-extensions',
  '--headless'
].compact
Watir::Browser.new(:chrome, **options)
```

**Comment by titusfortner** [comment] 2020-08-27 07:24
Thanks for the report, though I'm not certain where to go. I've seen these errors before with mismatched chrome / chromedriver versions, which doesn't seem to be your issue. 
@jdwolk @barelyknown @squanto -
Still seeing this issue with latest chrome/chromedriver?
Just chrome or other browsers as well?
How frequently does it happen?

You can turn set `$DEBUG = true` to get more details about all of the errors happening, but if it is very intermittent that might not be a good answer.

I'll keep this open for now, but there's not much I can do without being able to reproduce it.

**Comment by titusfortner** [comment] 2021-02-19 20:33
Closing this due to lack of update. Can re-open if we get a reproducible use case.

**Closed as completed by titusfortner** 2021-02-19 20:33 UTC
