### ISSUE TITLE
Chrome download prefs stopped working when passed as symbols; directory_upgrade option

### ISSUE THREAD

**Issue by chrisk** [watir/watir#893] opened 2020-04-05 18:13 UTC
## Meta -
Watir Version: 6.16.5
Chrome Version: 80.0.3987.149
selenium-webdriver Version: 3.142.7
OS Version: macOS 10.15.4
Ruby Version: 2.7.1

## Expected Behavior -
The instructions in the [Chrome guide](http://watir.com/guides/chrome/) and [Downloads guide](http://watir.com/guides/downloads/) should set the default download directory successfully.

```ruby
#!/usr/bin/env ruby

require "rubygems"
require "watir"

# This doesn't work

prefs = {
  download: {
    prompt_for_download: false,
    default_directory: File.expand_path("~/Desktop")
  }
}

b = Watir::Browser.new :chrome, options: {prefs: prefs}
b.goto "https://github.com/watir/watir/archive/master.zip"
sleep 5
```

## Actual Behavior -

It only works for me if you both:

1. Pass the preference names as strings, not symbols
2. Set `directory_upgrade` to `true`

```ruby
#!/usr/bin/env ruby

require "rubygems"
require "watir"

prefs = {
  download: {
    "prompt_for_download" => false,
    "directory_upgrade"   => true,
    "default_directory"   => File.expand_path("~/Desktop")
  }
}

b = Watir::Browser.new :chrome, options: {prefs: prefs}
b.goto "https://github.com/watir/watir/archive/master.zip"
sleep 5
```

## Steps to reproduce -

See above.

## Discussion - 

As far as `directory_upgrade`, is that just something that needs to be set? I'm not 100% clear on what it does based on the description in the [Chrome source](https://chromium.googlesource.com/chromium/src/+/20091257410486606a5042a4f4931cd916a087d1/chrome/common/pref_names.cc#1676) but it sounds like a security feature.

---

As far as the string keys, I hunted around in the related libraries for a bit. I do see that `selenium-webdriver` treats the `prefs` keys as though they are already strings in `Chrome::Options#add_preference` ([source](https://github.com/SeleniumHQ/selenium/blob/16cfc8304649f273ecfddbf4d97687010a232aa7/rb/lib/selenium/webdriver/chrome/options.rb#L131-L145)), but I'm not sure if that's related since I'm able to pass `:download` as a symbol successfully. It's the keys of the nested hash that need to be strings.

When I turn on all the logging, e.g.

```ruby
Watir.logger.level = :debug
Watir.logger.output = $stderr
Selenium::WebDriver.logger.level = :debug
Selenium::WebDriver.logger.output = $stderr
```

I can see that when the `download` prefs are symbols, this is what Selenium gets:

```
2020-04-05 14:53:11 INFO Selenium -> POST session
2020-04-05 14:53:11 INFO Selenium    >>> http://127.0.0.1:9515/session | {"desiredCapabilities":{"browserName":"chrome","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":false,"nativeEvents":false,"rotatable":false,"goog:chromeOptions":{"prefs":{"download":{"promptForDownload":false,"directoryUpgrade":true,"defaultDirectory":"/Users/chrisk/Desktop"}}}},"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"prefs":{"download":{"promptForDownload":false,"directoryUpgrade":true,"defaultDirectory":"/Users/chrisk/Desktop"}}}}]}}
```

As you can see, the keys we're interested in end up camel-cased. Whereas when I pass them as strings, this happens:

```
2020-04-05 14:55:57 INFO Selenium -> POST session
2020-04-05 14:55:57 INFO Selenium    >>> http://127.0.0.1:9515/session | {"desiredCapabilities":{"browserName":"chrome","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":false,"nativeEvents":false,"rotatable":false,"goog:chromeOptions":{"prefs":{"download":{"prompt_for_download":false,"directory_upgrade":true,"default_directory":"/Users/chrisk/Desktop"}}}},"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"prefs":{"download":{"prompt_for_download":false,"directory_upgrade":true,"default_directory":"/Users/chrisk/Desktop"}}}}]}}
```

---

Separately, I'm also getting a deprecation warning on Ruby 2.7.1 from some nearby code:

```
/Users/chrisk/.rvm/gems/ruby-2.7.1/gems/watir-6.16.5/lib/watir/capabilities.rb:85: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/chrisk/.rvm/gems/ruby-2.7.1/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/chrome/options.rb:45: warning: The called method `initialize' is defined here
```

I'm not sure if that's related, either.

**Comment by bieronym** [comment] 2020-04-22 03:10
I want to cry. I have searching for an answer over a month. Thank you very much
How did you even manage to find the solution? 

Also if you try to open the browser like this 

`browser=Watir::Browser.new :chrome, prefs: prefs, switches: switches`
(I dont know if this is correct)
it will still not work.
It must be in this format
`browser = Watir::Browser.new :chrome, options: {prefs: prefs, args: args}
`

**Comment by jkotests** [comment] 2020-05-15 04:12
The guides are correct for the expected format. The problem is that the latest versions of Selenium-WebDriver introduced a bug that has broken this - see https://github.com/SeleniumHQ/selenium/issues/7917. The Selenium project has created/merged a fix for this, but it has not yet been released.

**Comment by titusfortner** [comment] 2020-08-27 07:16
Selenium 4 alpha should be usable for ruby bindings. Let us know if this issue still exists for watir with the latest Selenium release.

**Closed as completed by titusfortner** 2020-08-27 07:16 UTC
