### ISSUE TITLE
StaleElementReferenceError on unreferenced iframes

### ISSUE THREAD

**Issue by matthewbyrne** [watir/watir#697] opened 2017-12-11 16:49 UTC
## Meta -
Watir Version: 6.10
Selenium Version: 3.8.0
Browser Version: FF 58.0b9
Browser Driver Version: geckodriver 0.19.0
OS Version: Ubuntu 14.04

## Expected Behavior -
No StaleElementReferenceError on unreferenced iframe elements

## Actual Behavior -
Unreferenced iframe elements are causing StaleElementReferenceError exceptions to be thrown.
The iframe exists on the page, but it never referenced in my code. It causes tests to crash unless I catch the exception.

iframes in general are a PITA in watir 6.X, and don't respond well to implicit or explicit waits.

```
Selenium::WebDriver::Error::StaleElementReferenceError: Exception The element reference of <iframe id="iframe-name"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
  Stack Trace:
  stack backtrace:
     0:           0x4f388c - backtrace::backtrace::trace::h736111741fa0878e
     1:           0x4f38c2 - backtrace::capture::Backtrace::new::h63b8a5c0787510c9
     2:           0x442d88 - webdriver::error::WebDriverError::new::hea6d4dbf778b2b24
     3:           0x44cecc - geckodriver::marionette::MarionetteSession::response::h98d048d51a7ee2ba
     4:           0x42c729 - <webdriver::server::Dispatcher<T, U>>::run::hba9181b5aacf8f04
     5:           0x402c59 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19de262639927233
     6:           0x40c065 - std::panicking::try::do_call::h6c1659fc4d01af51
     7:           0x5e38ec - panic_unwind::__rust_maybe_catch_panic
                          at /checkout/src/libpanic_unwind/lib.rs:98
     8:           0x420d32 - <F as alloc::boxed::FnBox<A>>::call_box::h953e5f59694972c5
     9:           0x5dc00b - alloc::boxed::{{impl}}::call_once<(),()>
                          at /checkout/src/liballoc/boxed.rs:661
                           - std::sys_common::thread::start_thread
                          at /checkout/src/libstd/sys_common/thread.rs:21
                           - std::sys::imp::thread::{{impl}}::new::thread_start
                          at /checkout/src/libstd/sys/unix/thread.rs:84
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:535:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/w3c/bridge.rb:441:in `element_tag_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/element.rb:86:in `tag_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/validator.rb:7:in `validate'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:164:in `block in filter_elements_by_locator'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:164:in `select!'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:164:in `filter_elements_by_locator'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:61:in `block in using_selenium'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:56:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:56:in `using_selenium'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/locators/element/locator.rb:46:in `locate_all'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/element_collection.rb:130:in `elements'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/element_collection.rb:70:in `to_a'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/element_collection.rb:29:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:660:in `count'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:660:in `rescue in element_call'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:679:in `element_call'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:403:in `visible?'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/elements/element.rb:426:in `present?'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:46:in `block in until'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:89:in `block in run_with_timer'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait/timer.rb:20:in `block in wait'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait/timer.rb:19:in `loop'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait/timer.rb:19:in `wait'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:88:in `run_with_timer'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:45:in `until'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:125:in `wait_until'
  /usr/local/lib/ruby/gems/2.3.0/gems/watir-6.10.0/lib/watir/wait.rb:173:in `wait_until_present'

```

## Steps to reproduce -
Company site, so nothing easy here. Hoping someones come across it before I need to go creating something.

**Comment by titusfortner** [comment] 2017-12-11 16:55
Hmm, IFrames code overall hasn't changed significantly since watir-webdriver v0.7

> never referenced in my code

What does this mean? Watir won't know about it unless it is referenced in your code.

Can you share the code you are using to get this stack trace?

**Comment by matthewbyrne** [comment] 2017-12-11 20:46
That's the odd thing. I'm actually not referencing it. I searched me repo for `iframe-name` and it's nowhere to be found. Not at my laptop at the moment, but the code it's failed on above is something like
`browser.div(:id => 'preview').wait_until(&:present)`

Other issues i've had with iframes is that `wait_until(&:present)` doesn't wait on the iframe element. I've had to do things like `browser.iframe(:id => 'someId').div.wait_until(&:exists)`. Using :present or leaving the div out gives me a timeout exception, saying it waited 30 seconds for the element to exist (it doesnt wait 30 seconds, it instantly checks and fails).

**Comment by titusfortner** [comment] 2017-12-11 22:24
Oh, hmm, ok, yeah, this is a geckodriver error message. 

The stack trace indicates that you are referencing an element in a collection, though. An iframe element will throw a stale exception error if the browsing context has been switched to inside that iframe. Somehow the collection you are iterating over is referencing an element from the wrong browsing context, which I'm not sure how that happens.

Can you run the test with `Selenium::WebDriver.logger.level = :info` and link to a gist with the results?

**Comment by titusfortner** [comment] 2017-12-12 12:00
Oh, this is interesting, that particular error is happening because of the new message code we put in there for checking inside iframes.
The real question is why we have to validate the tag names if that's all we're passing in. Looking further...

**Comment by titusfortner** [comment] 2017-12-12 12:23
Ok, I figured out the part I missed in the recent rewrite: 98fea98db5efac09a55d3b68113f31da8f457b4e

Once we get #698 agreed on, we'll do a point release.

**Comment by jkotests** [comment] 2017-12-13 04:22
@matthewbyrne, can you verify if v6.10.1 resolves the issue?

**Comment by matthewbyrne** [comment] 2017-12-13 12:21
Sure does. iframes are now respecting `wait_until(&:present?)`

Previously (v6.10) - Command would instantly execute and return the exception:
```
@browser.iframe(:id => 'iframe-id').wait_until(&:present?)
Watir::Exception::UnknownFrameException: unable to locate iframe using {:id=>"iframe-id", :tag_name=>"iframe"}
```

Latest (v6.10.1) - Command executes and waits for element:
```
@browser.iframe(:id => 'iframe-id').wait_until(&:present?)
 => #<Watir::IFrame: located: true; {:id=>"iframe-id", :tag_name=>"iframe"}>
```

**Comment by matthewbyrne** [comment] 2017-12-13 12:51
Slight update to this. 
There's still a problem with child elements.
While `@browser.iframe(:id => 'iframe-id').wait_until(&:present?)` works fine, `@browser.iframe(:id => 'iframe-id').body(:id =>'someBodyId').wait_until(&:present?)` fails because it's unable to find the iframe.

Using the now depricated `when_present` on the iframe solves this (though I assume this is still a bug).
eg. `@browser.iframe(:id => 'iframe-id').when_present.body(:id =>'someBodyId').wait_until(&:present?)`

**Comment by jkotests** [comment] 2017-12-13 17:56
Sorry @matthewbyrne. I'll take another look.

@titusfortner, I think the problem is that we switched to rescuing `unknown_exception` instead of the original `UnknownObjectException, UnknownFrameException`. Given a page without an iframe, when executing `browser.iframe.div.exists?`, the exception raised and `unknown_exception` will not match. Specifically, `#assert_exists` will raise `UnknownFrameException` but `unknown_exception` will be `UnknownObjectException`. Is this mismatch expected?

**Comment by titusfortner** [comment] 2017-12-13 18:06
I thought it wouldn't be an issue because we are testing from top down. Let me step through an example to verify; you might be right, and I might be wrong here. :)

**Comment by titusfortner** [comment] 2017-12-13 18:35
Yup, you were right, there was a reason we had that there. I added a test and did it the way you were going to do before I opened my mouth about it. :) 
I can do the release after the test suite has passed.

**Comment by titusfortner** [comment] 2017-12-13 20:03
@matthewbyrne please try 6.10.2

**Comment by matthewbyrne** [comment] 2017-12-13 20:20
Gave it a whirl in irb.
`@browser.iframe(:id => 'iframe-id').wait_until(&:present?)` waits for the element and returns the element
`@browser.iframe(:id => 'iframe-id').body.wait_until(&:present?)` waits for the element and returns the element

I'll try give it a run against our test suite tomorrow and report back if I spot any other issues. Cheers titus

**Comment by titusfortner** [comment] 2017-12-13 21:17
lol, well, you'd have had it a day before if I hadn't gotten in @jkotests way.
I'll close this, we can create something new if we find something else.

**Closed as completed by titusfortner** 2017-12-13 21:17 UTC
