### ISSUE TITLE
Waiting for element scope doesn't happen

### ISSUE THREAD

**Issue by abotalov** [watir/watir#759] opened 2018-07-31 14:12 UTC
## Meta -
I use nerodia but it mostly has the same implementation as Watir so I think bug is also reproducible for Watir.

## Expected Behavior -
I think Watir should do one (or both) of these things:
* Wait for element scope to be on the page (and raise TimeoutError if it's not present)
* Return empty list when iterating through `elements` if element scope is not on the page (so nothing will be raised in example below)

## Actual Behavior -
If query scope isn't present on the page, UnknownObjectException is raised.

## Steps to reproduce -
```
from nerodia import browser

br = browser.Browser()
br.goto("http://example.com")
els = br.element(id="a").elements(class_name="b")
for el in els:
  print el.text
```
This raises `UnknownObjectException: unable to locate element: #<HTMLElement: located: False; {'id': 'a'}>`

**Comment by titusfortner** [comment] 2018-08-01 00:58
Well, on the plus side this doesn't look like a regression; I don't think this has ever worked.

That being said I don't immediately see the fix for this. When we `#ensure_context` we probably shouldn't be ok with having a `nil` response. But just doing an `#assert_exists` like we did before still won't wait. If we `#wait_for_exists` we break a number of other specs... Let me thunk on it more.

In the meantime (though not lazy loaded):
```
els = br.element(id="a").wait_until(&:present?).elements(class_name="b")
```

**Comment by titusfortner** [comment] 2018-08-31 00:53
Ok, now I can't duplicate this in Watir with 6.12 code.

This code:
```
    Watir.default_timeout = 3
    browser.goto("http://example.com")
    els = browser.element(id: "a").elements(class_name: "b")
    els.first.text
```

Gives me this exception as expected:
```
Watir::Exception::UnknownObjectException: timed out after 3 seconds, waiting for #<Watir::HTMLElement: located: false; {:id=>"a"}> to be located
```

@lmtierney can you verify this is failing on current version of Nerodia?

**Comment by lmtierney** [comment] 2018-08-31 01:54
Yes, this has the same results

```
    import nerodia
    nerodia.default_timeout = 3
    browser = nerodia.browser.Browser()
    browser.goto("http://example.com")
    els = browser.element(id="a").elements(class_name="b")
    els[0].text
```

Gives
```
nerodia.exception.UnknownObjectException: timed out after 3 seconds, waiting for #<HTMLElement: located: False; {'id': 'a'}> to be located
```

**Comment by abotalov** [comment] 2018-08-31 07:27
`els[0].text` waits.
`for el in els` fails with `UnknownObjectException`

**Comment by lmtierney** [comment] 2018-08-31 12:32
@titusfortner indeed iterating still has that issue:
```
    Watir.default_timeout = 3
    browser.goto("http://example.com")
    els = browser.element(id: "a").elements(class_name: "b")
    els.each(&:text)
```
```
Watir::Exception::UnknownObjectException: unable to locate element: #<Watir::HTMLElement: located: false; {:id=>"a"}>
```

**Comment by lmtierney** [comment] 2018-08-31 13:36
Looks like the error comes from the `locate_all` call before iterating

```
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/elements/element.rb:592:in `assert_exists'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/elements/element.rb:393:in `wd'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/locators/element/locator.rb:267:in `ensure_scope_context'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/locators/element/locator.rb:128:in `create_normalized_selector'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/locators/element/locator.rb:60:in `using_watir'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/locators/element/locator.rb:42:in `locate_all'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/element_collection.rb:153:in `elements'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/element_collection.rb:88:in `to_a'
	from /home/lucas/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/watir-6.12.0/lib/watir/element_collection.rb:29:in `each'
	from (irb):6
	from /home/lucas/.rbenv/versions/2.3.4/bin/irb:11:in `<main>'
```

**Closed as completed** 2018-09-11 21:10 UTC
